/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Echarts: typeof import('../../hooks/useEcharts')['Echarts']
  const Fequest: typeof import('../../hooks/useFech')['Fequest']
  const StorageKeys: typeof import('../../hooks/useLocalStore')['StorageKeys']
  const computed: typeof import('vue')['computed']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineEmits: typeof import('vue')['defineEmits']
  const defineProps: typeof import('vue')['defineProps']
  const markRaw: typeof import('vue')['markRaw']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const ref: typeof import('vue')['ref']
  const storage: typeof import('../../hooks/useLocalStore')['storage']
  const useDebounce: typeof import('../../hooks/useVue')['useDebounce']
  const useEventListener: typeof import('../../hooks/useVue')['useEventListener']
  const useFequest: typeof import('../../hooks/useFech')['useFequest']
  const useResize: typeof import('../../hooks/useVue')['useResize']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Echarts } from '../../hooks/useEcharts'
  import('../../hooks/useEcharts')
  // @ts-ignore
  export type { CommonResult } from '../../hooks/useFech'
  import('../../hooks/useFech')
  // @ts-ignore
  export type { StorageKeys } from '../../hooks/useLocalStore'
  import('../../hooks/useLocalStore')
}
